version: "3.0"
services:
  redis:
    image: redis
    container_name: fcfs_redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --maxmemory 2G --maxmemory-policy allkeys-lru
    networks:
      - local_network

  zookeeper:
    container_name: local-zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: fcfs-kafka
    image: bitnami/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test:1:1" # Topic명:Partition개수:Replica개수
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local_network:
